blank_issues_enabled: false

contact_links:
  - name: ğŸ› Report a problem
    url: https://github.com/zoonk/website/discussions/new?category=problems
    about: Report a problem that needs to be fixed.

  - name: ğŸ’¡ Make a suggestion
    url: https://github.com/zoonk/website/discussions/new?category=ideas
    about: Share any ideas you have to improve how we work.

  - name: ğŸ™ Ask a question
    url: https://github.com/zoonk/website/discussions/new?category=q-a
    about: Ask any questions you have.
